import { useEffect, useRef, useState } from 'react'
import { WebGLOrb } from './components/WebGLOrb'
import { LiveWaveform } from './components/LiveWaveform'
import { MessageFeed } from './components/MessageFeed'
import { useLiveKitAgent } from './hooks/useLiveKitAgent'
import { useStore } from './lib/store'

// Extend Window interface for global readiness state
declare global {
  interface Window {
    voiceAgentReady: boolean
    voiceAgentStatus: {
      ready: boolean
      connected: boolean
      agentConnected: boolean
      audioReady: boolean
      error: string | null
      timestamp: number
    }
  }
}

function App() {
  // Get URL parameters for LiveKit connection
  //   - livekit_url: LiveKit server URL (wss://...)
  //   - token: LiveKit room token (JWT)
  const params = new URLSearchParams(window.location.search)
  const livekitUrl = params.get('livekit_url') || params.get('livekit')
  const livekitToken = params.get('token') || params.get('livekit_token')
  const hasConnectionParams = !!(livekitUrl && livekitToken)

  // Track if we've signaled readiness
  const readinessSignaled = useRef(false)

  // CONNECTION-GATED RENDERING: Only show full UI when ready
  const [showUI, setShowUI] = useState(false)

  // Initialize LiveKit agent hook
  const agent = useLiveKitAgent()

  const {
    agentState,
    agentConnected,
    audioStatus,
    inputVolume,
    outputVolume,
    messages,
    toolCalls
  } = useStore()

  // Connect to LiveKit when parameters are available
  useEffect(() => {
    if (livekitUrl && livekitToken) {
      agent.connect(livekitUrl, livekitToken)
    }

    return () => {
      agent.disconnect()
    }
  }, [livekitUrl, livekitToken])

  // Get connection status
  const { isConnected, error } = agent

  // Determine if fully ready
  const isFullyReady = isConnected && agentConnected

  // CONNECTION-GATED RENDERING: Reveal UI when connected + agent detected
  useEffect(() => {
    if (isFullyReady && !showUI) {
      // Small delay to ensure audio tracks are subscribed
      const timer = setTimeout(() => setShowUI(true), 300)
      return () => clearTimeout(timer)
    }
  }, [isFullyReady, showUI])

  // Update global readiness state for Recall.ai to check
  useEffect(() => {
    const isReady = isConnected && agentConnected && audioStatus === 'playing'

    // Update global status object (always)
    window.voiceAgentStatus = {
      ready: isReady,
      connected: isConnected,
      agentConnected: agentConnected,
      audioReady: audioStatus === 'playing',
      error: error,
      timestamp: Date.now()
    }

    // Update simple ready flag
    window.voiceAgentReady = isReady

    // Log readiness once when first achieved
    if (isReady && !readinessSignaled.current) {
      readinessSignaled.current = true
      console.log('VOICE_AGENT_READY - Page fully initialized and ready for meeting')

      // Dispatch custom event that Recall.ai can listen for
      window.dispatchEvent(new CustomEvent('voiceAgentReady', {
        detail: window.voiceAgentStatus
      }))
    }
  }, [isConnected, agentConnected, audioStatus, error])

  // ============================================================
  // RENDERING LOGIC
  // ============================================================

  // If no connection params, show instructions (development mode)
  if (!hasConnectionParams) {
    return (
      <div className="min-h-screen bg-white flex flex-col items-center justify-center overflow-hidden">
        <div className="p-6 bg-white/60 backdrop-blur-sm rounded-2xl border border-gray-200/50 max-w-md">
          <h3 className="text-lg font-semibold text-gray-800 mb-2">
            Connect to Voice Agent
          </h3>
          <p className="text-sm text-gray-600 mb-4">
            Add URL parameters to connect via LiveKit:
          </p>
          <code className="block p-3 bg-gray-100 rounded-lg text-xs font-mono text-gray-700 break-all">
            ?livekit_url=wss://your-project.livekit.cloud&token=JWT_TOKEN
          </code>
          <p className="text-xs text-gray-500 mt-3">
            The token is generated by your backend when joining a LiveKit room.
          </p>
        </div>
      </div>
    )
  }

  // WHILE CONNECTING: Show only the orb (no text states)
  // The orb animates in a muted "connecting" visual state
  if (!showUI) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center overflow-hidden">
        <WebGLOrb
          agentState={null}
          inputVolume={0}
          outputVolume={0}
          isConnected={false}
          size={280}
        />
      </div>
    )
  }

  // FULLY CONNECTED: Show complete UI - user sees "Ready" immediately
  return (
    <div className="min-h-screen bg-white flex flex-col items-center justify-center overflow-hidden">

      {/* Main content container */}
      <div className="relative z-10 w-full max-w-2xl px-6 py-8 flex flex-col items-center">

        {/* LiveKit badge - top left */}
        <div className="absolute top-4 left-4">
          <span className="px-2 py-1 text-xs font-medium rounded-full bg-[#4EEAAA]/20 text-[#1A1A1A]">
            LiveKit
          </span>
        </div>

        {/* Hero: WebGL Orb */}
        <div className="flex-1 flex items-center justify-center py-12">
          <WebGLOrb
            agentState={agentState}
            inputVolume={inputVolume}
            outputVolume={outputVolume}
            isConnected={true}
            size={280}
          />
        </div>

        {/* Input waveform - shows when listening */}
        {agentState === 'listening' && (
          <div className="w-full max-w-md mb-8 animate-fade-in">
            <LiveWaveform
              active={true}
              barColor="rgba(78, 234, 170, 0.7)"
              height={48}
            />
          </div>
        )}

        {/* Agent state label - NO "Connecting" states ever shown */}
        <div className="mb-8 text-center">
          <p className="text-sm font-medium text-gray-400 uppercase tracking-wider">
            {agentState === 'listening' && 'Listening...'}
            {agentState === 'thinking' && 'Processing...'}
            {agentState === 'speaking' && 'Speaking...'}
            {!agentState && 'Ready'}
          </p>
        </div>

        {/* Message feed */}
        <div className="w-full">
          <MessageFeed
            messages={messages}
            toolCalls={toolCalls}
          />
        </div>

        {/* Error display */}
        {error && (
          <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl">
            <p className="text-sm text-red-600">{error}</p>
          </div>
        )}
      </div>

      {/* SYNRG branding - bottom */}
      <div className="absolute bottom-6 text-center">
        <img
          src="/synrg-logo.png"
          alt="SYNRG"
          className="h-10 w-auto mx-auto"
        />
        <p className="text-xs text-gray-400 mt-2 tracking-wider">
          VOICE ASSISTANT
        </p>
      </div>
    </div>
  )
}

export default App
